# Generated by Django 4.2.1 on 2023-06-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_userfollow_followers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollow',
            old_name='starting_to_follow',
            new_name='is_now_following',
        ),
    ]
