# Generated by Django 4.2.1 on 2023-06-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_rename_starting_to_follow_userfollow_is_now_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
