# Generated by Django 4.2.1 on 2023-06-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_userfollow_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.UniqueConstraint(fields=('user', 'is_now_following'), name='unique-following-follower'),
        ),
    ]
