# Generated by Django 4.2.1 on 2023-06-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
