# Generated by Django 4.2.1 on 2023-06-13 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
