# Generated by Django 4.2.1 on 2023-06-14 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_comment_parent_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='network.comment'),
        ),
    ]
