# Generated by Django 4.2.1 on 2023-06-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0033_remove_post_comments_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
