# Generated by Django 4.2.1 on 2023-06-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0034_remove_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
