# Generated by Django 4.2.1 on 2023-06-18 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0035_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
