# Generated by Django 4.2.1 on 2023-06-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0036_remove_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='Welcome to my account!', max_length=150),
        ),
    ]
