# Generated by Django 4.2.1 on 2023-06-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0037_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(default='Welcome to my account!', max_length=350),
        ),
    ]
