# Generated by Django 4.2.1 on 2023-06-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0038_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/Users/emrakh/CS50W/project4/network/static/network/images/default.jpeg', upload_to='static/network/images/'),
        ),
    ]
