# Generated by Django 4.2.1 on 2023-06-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0041_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='network/images/default.jpeg', upload_to='network/images/'),
        ),
    ]
