# Generated by Django 4.2.4 on 2023-08-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0049_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/static/network/media/images/default.jpeg', upload_to='images'),
        ),
    ]
